version = 1
disableParticles = false
byTypeReductions = {  }
maxParticlesPerSheet = 4096
particleRenderDistanceMultiplier = 0.5
asynchronousTicking = true
reduceAllChance = 0.25
reduceDecreasedChance = 0.5
turnOffPotionParticlesV2 = [
    "NONE"
]
